### ISSUE TITLE
Editor settings button behavioral issues

### ISSUE THREAD

**Issue by bmc75** [CodePen/redesign#141]
When you click the Settings button the dialog box opens. Clicking outside the dialog box closes it as expected but then when you click Settings again nothing happens until you click it a second time. I shot a (poor) screen capture showcasing this:

http://g.recordit.co/3kv2mGxM7c.gif

Update: This happens with any of the settings "cog" icons as well in a similar behavior.

**Comment by chriscoyier** [comment]
Good catch! For now I'm going to fix this by making the click-away action NOT close the settings modal. You can close it by using the same button again or the big green one inside. 

It's tricky because the settings modal is a special case where we open an close it as part of the Pen's state, so we can sync that state through Professor Mode. So if we do the click-away-to-close thing (cc @quezo) then it needs to somehow be aware that it's closing the settings dialog and update and deal with state accordingly.
