### ISSUE TITLE
Change view button closes settings panel and then two clicks are required to open settings

### ISSUE THREAD

**Issue by marcusstenbeck** [CodePen/redesign#148]
Steps to reproduce

1. click "change view" in editor (001)
2. click "settings"
3. click "change view"

**expected:** change view modal should close and settings should stay
**actual:** both modals close and now settings button must be clicked twice to open settings modal again

Chrome OSX Version 45.0.2454.101 (64-bit)

![](http://g.recordit.co/GrgEKph340.gif)

**Comment by chriscoyier** [comment]
This is pretty much fixed. It's not quite perfect, but it's better. 

The settings dialog is it's own unique beast, unlike other dropdowns (the reason is that it's part of the STATE of the editor, which we can then sync, like for Professor Mode). 

I think what I'll do it style it a bit differently so it will feel more like the modal, and thus have less expectation that it behaves exactly like other dropdowns.

**Comment by marcusstenbeck** [comment]
Excellent! 🙏
