### ISSUE TITLE
FOUC on pen page show big icons

### ISSUE THREAD

**Issue by yukulele** [CodePen/redesign#174]
![codepen.io/pen FOUC](https://cloud.githubusercontent.com/assets/347244/10249807/7e082794-6927-11e5-91e9-d45390a9e0cd.PNG)

**Comment by chriscoyier** [comment]
Does this happen every single time you load the page? I've never actually seen it, but it's certainly possible. If the CSS didn't load at all, that's about what you would see. Our SVG system doesn't put width or height attributes on the SVG's, they are all set in CSS. It could be fixed a bit if I rejiggered the system to put width and heights on every SVG around the whole site, but it's not much of a fix because if the CSS doesn't load, the site is pretty unusable anyway. It's probably better for us to figure out why you're seeing FOUC at all, when we load CSS in the header in a blocking fashion. So yeah I guess first question again: Does this happen every single time you load the page?
