### ISSUE TITLE
Add Runtime for Babel? (maybe)

### ISSUE THREAD

**Issue by yukulele** [CodePen/redesign#175]
when I use babel with generator function or ES7 async/await function I have an error:
```
ReferenceError: regeneratorRuntime is not defined
```
please, can you make Codepen add automatically regeneratorRuntime when needed?

**Comment by tsabat** [comment]
Hi, we don't use babel around this joint.  Can you help us understand what needs to be added?

**Comment by tsabat** [comment]
is it this?  https://babeljs.io/docs/usage/runtime/

**Comment by yukulele** [comment]
Exactly! `--optional runtime` should done the job

**Comment by chriscoyier** [comment]
I always feel a little weird about this stuff - having so little knowledge of what it does exactly or what the performance considerations are. But hey I guess if it works and makes more things possible without hurting anything else I'm for it.

**Comment by yukulele** [comment]
This option simply make Babel add a little piece of code if my script use generators.
Because this piece of code could be used by other scripts in an app, Babel don't include it by default to avoid include it on file using generators.
In Codepen their is single script, so, it's ok.

**Comment by developit** [comment]
I would love to see this land in CodePen.  The regenerator runtime is required in order to use ES7 [async/await](http://pouchdb.com/2015/03/05/taming-the-async-beast-with-es7.html) and [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*).

Right now your babel configuration will transpile both new syntaxes, but the output requires the (regenerator) runtime, which is not present.  It's fairly small and maintained by Facebook.

**Comment by tholman** [comment]
Moved this into our internal tracking board, since its not really a redesign bug. 

Awesome suggestion!

**Comment by yukulele** [comment]
Thanks @tholman!
