### ISSUE TITLE
Hearting a blog post, the heart still shows white in Firefox

### ISSUE THREAD

**Issue by thebabydino** [CodePen/redesign#182]
It turns pink in Chrome, but stays white in Firefox (41 on Windows 8).

**Comment by tholman** [comment]
The svg's definitions fill may need to be set to inherit, where its defined.

**Comment by chriscoyier** [comment]
fixing...

Here's the scoop though which confused the heck out of me.

Say you have

```
<a href="#0" class="button">
<svg class="heart">
  <use xlink:href="#heart" />
</svg>
</a>
```

then

```
.button svg {
  fill: white;
}
```

You'd think THIS would win:

```
.button .heart {
  fill: pink;
}
```

And it does in Chrome, but not in Firefox.

I think because the DOM sorta ends up like 

```
<A>
  <SVG>
     <SVG>
```

in Firefox and thus the INNER svg is more specifically targeted by that first selector.
