### ISSUE TITLE
Switching between Team and Personal account context triggers error modal

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#242]
Members switching from a Team context to Personal context report "Error is not a valid URL" modal. 

Screenshot submitted by email. I've removed the member's name & team name from this image:
![team-pers-switch-error](https://cloud.githubusercontent.com/assets/456844/10371310/b7a62e28-6db0-11e5-92fe-04329f26909c.png)

**Comment by tsabat** [comment]
So, the problem is this: we tried to improve the site during the redesign by adding URL validation on save.  But, we put the validation on the object instead of the service.  This means that for most people, the user object saves fine when you do something like save user.current_team_id.  But, if you've got a profile that looks like this:

![screen shot on 2015-10-08 at 14-13-43](https://cloud.githubusercontent.com/assets/636041/10380163/16ef8364-6dc7-11e5-997a-e875d15a80fd.png)

You're unable to switch profiles.  Same would go for queued screenshots, etc.  So, we're removing the validation for now, and will apply at the service level instead of at model level.

**Comment by robinrendle** [comment]
👍Everything is a-ok now!
