### ISSUE TITLE
page scrolls on arrow-keys in comments

### ISSUE THREAD

**Issue by pixelass** [CodePen/redesign#254]
If I press an arrow key while in a comment the page scrolls up

(See gif: I am pressing the right arrow of my keyboard)

![scroll to top issue](https://cloud.githubusercontent.com/assets/1148334/10402908/f5cc5c0a-6e7c-11e5-9fe4-7c1b32c02d05.gif)

**Comment by tbremer** [comment]
Noticed this one as well today. For me this happened on all major browsers (Safari, Chrome, FireFox) on OS X El Capitan.

It did not happen if a modifier key (`cmd` in my case) was also pressed.

**Comment by jakealbaugh** [comment]
For what it's worth, similar issues have been around since before the redesign. 

Pagination arrow key binding is a big one too. Reprod:

1. http://codepen.io/chriscoyier/pens/popular/
2. type in "Search Chris Coyier pens" input
3. move cursor around word with arrow keys
4. pagination of pens updates

This happens globally, e.g. home page + main search. It's any combo of text input and key-controlled pagination.
