### ISSUE TITLE
middle click on user avatar image

### ISSUE THREAD

**Issue by ge1doot** [CodePen/redesign#295]
"Middle" mouse click on the avatar icon (between the new pen button and the search icon)

I would expect the browser to open my profile in a new tab... (or at least open the menu, like with the activity icon)

**Comment by quezo** [comment]
@ge1doot Is this a normal browser response to a link or something you have to code for? We don't ever take actions based on which mouse button you click since not all mouses have more than one button.

**Comment by ge1doot** [comment]
well... it's a minor thing and maybe it's due to some of my extensions. But on windows, the normal navigation response of any browser when you click any regular link with the wheel button or middle button (if present) is to open the link in a new tab. Nothing you have to code for. The problem here is probably due to the fact the avatar icon is not a regular a href link but just an image and you manage the mouse events with javascript.

**Comment by chriscoyier** [comment]
Yeah I could see how it would be nice if that was a link to your profile. I'm afraid it just isn't a link at all right now, just a way to let you know you're logged in and a tap target for the dropdown. In the redesign we made it consistent that all dropdowns are tap-to-open, so this is inline with that. I'm not sure we'll be able to support that concept with supporting the middle-click thing too. But maybe! Maybe it could be a link that we disable with JavaScript and re-enable with the dropdown is open or something weird. For now we're going to wait for more feedback, since this is the first sort-of-negative feedback we've heard on it.
