### ISSUE TITLE
Incorrect heading outline on pen detail page

### ISSUE THREAD

**Issue by MichielBijl** [CodePen/redesign#300]
Pen's title is a `h1`, which is good. Description title is a `h4`, where did `h2` and `h3` go? Same thing with the tags and comments titles.

**Comment by chriscoyier** [comment]
I bet there is a header outline problem on every page I've ever touched in my entire career. Not that that's an excuse mind you. In this case, I just don't wanna chase this down one page at a time and end up in a confusing `<h2 class="making-this-look-like-a-h4-because-outline">` situation. I'm going to move this to our internal **accessibility problems** thread and hopefully we can do a sprint on that soon.

**Comment by MichielBijl** [comment]
Awesome :)
